// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmVGiFORFrAiymTYhBoqHU6Vn_gXvK2GM',
    appId: '1:3240696803:android:6dc063fde1cc6f1fbe5ed6',
    messagingSenderId: '3240696803',
    projectId: 'sptech-merchant',
    storageBucket: 'sptech-merchant.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuxomhw_EaixfaUwonRH8tdXwl5DFYdIA',
    appId: '1:3240696803:ios:f16e942e02675204be5ed6',
    messagingSenderId: '3240696803',
    projectId: 'sptech-merchant',
    storageBucket: 'sptech-merchant.appspot.com',
    androidClientId: '3240696803-3ar7l1s3n3d3904tcth0qic34bpru5jj.apps.googleusercontent.com',
    iosClientId: '3240696803-gavs9f37prauee6q73pcijsgadksbcot.apps.googleusercontent.com',
    iosBundleId: 'com.sptech.merchant',
  );
}
